const $=x=>document.getElementById(x);
let level=Number(localStorage.joLevel||1),score=Number(localStorage.joScore||0);
const games=['Memory Match','Tap Rush','Odd One Out','Higher or Lower','Reaction Championship','Lucky Doors','Maths Blitz','Sequence Memory','Emoji Hunt','Treasure Vault','Word Scramble','Stop the Clock','Number Memory','Quick Choice','Pattern Hunt','Target Chase','True or False','Card Hunt','Fast Maths','Jackpot Challenge'];
const defaults=[
{name:'Proper Kiss',text:'A long lingering kiss from Gary.',type:'normal',cost:2500},
{name:'Naughty Massage',text:'A private massage with the mood chosen by Jo.',type:'normal',cost:4000},
{name:'You Choose Tonight',text:'Jo chooses the romantic plan for the evening.',type:'normal',cost:5000},
{name:'Secret Request',text:'Jo gets one private mutually-agreed request.',type:'normal',cost:6500},
{name:'Mystery Date',text:'Gary arranges a surprise date for you both.',type:'normal',cost:8000},
{name:'Breakfast Treat',text:'Breakfast or brunch chosen by Jo.',type:'normal',cost:3000},
{name:'After Dark Jackpot',text:'A special private reward you both agree on together.',type:'dark',cost:12000},
{name:'Fantasy Night',text:'Choose a private fantasy or scenario you both want.',type:'dark',cost:15000}
];
const tier=()=>Math.floor((level-1)/5);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function save(){localStorage.joLevel=level;localStorage.joScore=score}
function hud(){ $('title').textContent='Level '+level+' · '+games[(level-1)%games.length];$('score').textContent='Balance: '+score.toLocaleString()+' points';$('difficulty').textContent='Difficulty '+(tier()+1)}
function prizes(){try{let a=JSON.parse(localStorage.getItem('joAdminPrizes')||'[]');if(Array.isArray(a)&&a.length)return a.map((x,i)=>({...x,cost:Number(x.cost)||defaultCost(x.type,i)}))}catch(e){}return defaults}
function defaultCost(type,i){return type==='dark'?12000+(i%3)*1500:2500+(i%6)*1000}
function history(){try{return JSON.parse(localStorage.getItem('joRedeemedRewards')||'[]')}catch(e){return[]}}
function showGame(){ $('shop').hidden=true;$('gameView').hidden=false;load() }
function showShop(){ $('gameView').hidden=true;$('shop').hidden=false;renderShop() }
function renderShop(){hud();const list=$('shopList');list.innerHTML='';prizes().forEach((p,i)=>{let c=document.createElement('div');c.className='shopCard';let h=document.createElement('h3');h.textContent=(p.type==='dark'?'🔥 ':'🎁 ')+p.name;let d=document.createElement('p');d.textContent=p.text||'';let cost=document.createElement('strong');cost.textContent=Number(p.cost).toLocaleString()+' points';let b=document.createElement('button');b.textContent=score>=p.cost?'Redeem':'Need '+(p.cost-score).toLocaleString()+' more';b.disabled=score<p.cost;b.onclick=()=>redeem(p);c.append(h,d,cost,b);list.appendChild(c)});let r=history();$('redeemed').innerHTML=r.length?'<h3>Redeemed</h3>'+r.slice().reverse().map(x=>'<div class="redeemedItem">✓ '+escapeHtml(x.name)+' · '+Number(x.cost).toLocaleString()+' pts</div>').join(''):'<p class="muted">Nothing redeemed yet.</p>'}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function redeem(p){if(score<p.cost)return;if(!confirm('Redeem '+p.name+' for '+Number(p.cost).toLocaleString()+' points?'))return;score-=p.cost;save();let r=history();r.push({name:p.name,text:p.text||'',cost:p.cost,at:new Date().toISOString()});localStorage.setItem('joRedeemedRewards',JSON.stringify(r));alert('Redeemed: '+p.name+' 🎉');renderShop()}
function finish(base=500){let bonus=base+Math.min(750,tier()*75);score+=bonus;save();$('stage').hidden=true;$('reward').hidden=false;$('rewardTitle').textContent='🏆 Level complete!';$('prize').textContent='+'+bonus.toLocaleString()+' points';$('prizeText').textContent='Banked! Balance: '+score.toLocaleString()+' points.';$('next').textContent='Next game';hud()}
$('next').onclick=()=>{level++;save();load()};$('shopBtn').onclick=showShop;$('backBtn').onclick=showGame;
const btn=(txt,fn)=>{let b=document.createElement('button');b.textContent=txt;b.className='gameBtn';b.onclick=fn;return b};
function memory(){let pairs=clamp(5+Math.floor(tier()/2),5,8),symbols=['💎','💋','🌹','⭐','🍀','❤️','🎁','🔥'].slice(0,pairs),a=symbols.flatMap(x=>[x,x]).sort(()=>Math.random()-.5),open=[],found=0;$('desc').textContent='Match all '+pairs+' pairs.';$('stage').innerHTML='';a.forEach(x=>{let b=btn('?',()=>{if(b.disabled||open.length===2)return;b.textContent=x;b.disabled=true;open.push(b);if(open.length===2){let[p,q]=open;if(p.textContent===q.textContent){found++;open=[];if(found===pairs)finish()}else setTimeout(()=>{p.textContent=q.textContent='?';p.disabled=q.disabled=false;open=[]},clamp(650-tier()*30,320,650))}});b.style.width='21%';$('stage').appendChild(b)})}
function tapRush(){let n=0,need=clamp(18+tier()*2,18,40),limit=clamp(13000-tier()*350,7000,13000),start=Date.now();$('desc').textContent='Hit '+need+' moving targets in '+(limit/1000).toFixed(1)+' seconds.';function go(){if(Date.now()-start>limit){n=0;start=Date.now()}$('stage').innerHTML='';let b=btn('🎯 '+n+'/'+need,()=>{n++;n>=need?finish(650):go()});b.style.cssText='position:relative;width:34%;height:90px;margin-left:'+Math.floor(Math.random()*60)+'%;margin-top:'+Math.floor(Math.random()*150)+'px';$('stage').appendChild(b)}go()}
function odd(){let r=0,need=clamp(5+Math.floor(tier()/2),5,10);$('desc').textContent='Find the odd symbol '+need+' times.';function go(){let count=clamp(10+tier()*2,10,26),a=Array(count).fill('💗'),i=Math.floor(Math.random()*count);a[i]='💖';$('stage').innerHTML='';a.forEach((x,j)=>{let b=btn(x,()=>{r=j===i?r+1:Math.max(0,r-1);r>=need?finish():go()});b.style.width='21%';$('stage').appendChild(b)})}go()}
function hilo(){let cur=1+Math.floor(Math.random()*9),wins=0,need=clamp(5+Math.floor(tier()/2),5,10);$('desc').textContent='Call '+need+' numbers correctly. A miss costs progress.';function draw(){$('stage').innerHTML='<h2 class="bigNum">'+cur+'</h2>';$('stage').append(btn('Higher',()=>guess(1)),btn('Lower',()=>guess(0)))}function guess(h){let n=1+Math.floor(Math.random()*9);if(n===cur)n=cur===9?8:cur+1;wins=(n>cur)==h?wins+1:Math.max(0,wins-1);cur=n;wins>=need?finish():draw()}draw()}
function reaction(){let round=0,times=[],ready=false,timer,rounds=clamp(4+Math.floor(tier()/2),4,8),target=clamp(700-tier()*18,430,700);$('desc').textContent=rounds+' reaction rounds. Average under '+target+'ms.';function go(){ready=false;$('stage').innerHTML='';let b=btn('WAIT…',()=>{if(!ready){clearTimeout(timer);b.textContent='TOO SOON';setTimeout(go,600)}else{times.push(performance.now()-b.go);round++;if(round===rounds){let avg=Math.round(times.reduce((a,c)=>a+c,0)/rounds);if(avg<=target){$('desc').textContent='Average: '+avg+'ms';finish(750)}else{$('desc').textContent='Average '+avg+'ms. Need '+target+'ms or better.';round=0;times=[];setTimeout(go,1100)}}else go()}});b.style='width:100%;height:220px;font-size:36px';$('stage').append(b);timer=setTimeout(()=>{ready=true;b.textContent='GO!';b.go=performance.now()},800+Math.random()*2200)}go()}
function doors(){let round=0,need=clamp(2+Math.floor(tier()/2),2,6),doors=clamp(3+Math.floor(tier()/3),3,6);$('desc').textContent='Find '+need+' keys.';function go(){let win=Math.floor(Math.random()*doors);$('stage').innerHTML='';for(let i=0;i<doors;i++)$('stage').append(btn('🚪',()=>{if(i===win){round++;round>=need?finish():go()}else{round=Math.max(0,round-1);go()}}))}go()}
function maths(){let n=0,need=clamp(5+tier(),5,12),wrong=0;$('desc').textContent='Solve '+need+' sums. Three mistakes reset the streak.';function q(){let hard=tier()>=2,a=2+Math.floor(Math.random()*(10+tier()*3)),b=2+Math.floor(Math.random()*(8+tier()*2)),mul=hard&&Math.random()<clamp(.2+tier()*.04,.2,.55),ans=mul?a*b:a+b;$('stage').innerHTML='<h2>'+a+(mul?' × ':' + ')+b+' = ?</h2><input id="ans" inputmode="numeric" class="answer"><button id="ok" class="gameBtn">Answer</button>';$('ok').onclick=()=>{if(+$('ans').value===ans){n++;wrong=0;n>=need?finish():q()}else{wrong++;$('ans').value='';if(wrong>=3){n=0;wrong=0}}}}q()}
function sequence(){let seq=[],goal=clamp(5+tier(),5,10);$('desc').textContent='Repeat the sequence. Reach '+goal+' steps.';function newRound(){seq.push(1+Math.floor(Math.random()*4));$('stage').innerHTML='<h2 class="sequence">'+seq.join('  ')+'</h2>';setTimeout(play,clamp(850+seq.length*170-tier()*35,650,1900))}function play(){let pos=0;$('stage').innerHTML='';[1,2,3,4].forEach(x=>$('stage').append(btn(x,()=>{if(x===seq[pos]){pos++;if(pos===seq.length){seq.length>=goal?finish(700):setTimeout(newRound,300)}}else{seq=[];setTimeout(newRound,450)}})))}newRound()}
function emojiHunt(){let r=0,need=clamp(5+tier(),5,12),count=clamp(16+tier()*2,16,30);$('desc').textContent='Find the requested emoji '+need+' times.';const es=['🍕','🐶','💎','❤️','🌹','🔥','⭐','🍀'];function go(){let target=es[Math.floor(Math.random()*es.length)],a=Array.from({length:count},()=>es[Math.floor(Math.random()*es.length)]);a[Math.floor(Math.random()*count)]=target;$('stage').innerHTML='<h3>Find: '+target+'</h3>';a.forEach(x=>$('stage').append(btn(x,()=>{if(x===target){r++;r>=need?finish():go()}else r=Math.max(0,r-1)})))}go()}
function treasure(){let lives=clamp(4-Math.floor(tier()/3),2,4),maxLives=lives,found=0,need=clamp(3+Math.floor(tier()/2),3,7),cells=clamp(6+tier(),6,12);$('desc').textContent='Find '+need+' treasures before losing all lives.';function go(){let win=Math.floor(Math.random()*cells);$('stage').innerHTML='<p>Treasure '+found+'/'+need+' · Lives '+lives+'</p>';for(let i=0;i<cells;i++)$('stage').append(btn('❓',()=>{if(i===win){found++;found>=need?finish(700):go()}else{lives--;if(lives<=0){lives=maxLives;found=0}go()}}))}go()}
function scramble(){let words=['wedding','champagne','diamond','romance','flowers','honeymoon','dancing','forever','celebrate','adventure','beautiful','memories'],n=0,need=clamp(4+Math.floor(tier()/2),4,8);$('desc').textContent='Unscramble '+need+' words.';function q(){let pool=words.filter(w=>w.length<=7+tier()),w=pool[Math.floor(Math.random()*pool.length)],s=w.split('').sort(()=>Math.random()-.5).join('');$('stage').innerHTML='<h2>'+s.toUpperCase()+'</h2><input id="word" class="answer"><button id="ok" class="gameBtn">Check</button>';$('ok').onclick=()=>{if($('word').value.trim().toLowerCase()===w){n++;n>=need?finish():q()}else $('word').value=''}}q()}
function stopClock(){let target=5,width=clamp(.35-tier()*.025,.12,.35);$('desc').textContent='Stop between '+(target-width).toFixed(2)+' and '+(target+width).toFixed(2)+' seconds.';function go(){let st=performance.now();$('stage').innerHTML='';let b=btn('STOP',()=>{let t=(performance.now()-st)/1000;$('desc').textContent='You stopped at '+t.toFixed(2)+'s.';if(Math.abs(t-target)<=width)finish(800);else setTimeout(go,800)});b.style='width:100%;height:220px;font-size:40px';$('stage').append(b)}go()}
function numberMemory(){let r=3,goal=clamp(6+tier(),6,11);$('desc').textContent='Remember numbers up to '+goal+' digits.';function q(){let s='';for(let i=0;i<r;i++)s+=Math.floor(Math.random()*10);$('stage').innerHTML='<h2 class="bigNum">'+s+'</h2>';setTimeout(()=>{$('stage').innerHTML='<input id="num" inputmode="numeric" class="answer"><button id="ok" class="gameBtn">Submit</button>';$('ok').onclick=()=>{if($('num').value===s){r++;r>goal?finish(750):q()}else{r=Math.max(3,r-1);q()}}},clamp(1050+r*140-tier()*35,700,1800))}q()}
function quickChoice(){let r=0,need=clamp(8+tier(),8,16);$('desc').textContent='Tap the larger number. Get '+need+' in a row.';function q(){let max=99+tier()*50,a=Math.floor(Math.random()*max)+1,b=Math.floor(Math.random()*max)+1;if(a===b)b++;$('stage').innerHTML='';$('stage').append(btn(a,()=>hit(a>b)),btn(b,()=>hit(b>a)))}function hit(ok){r=ok?r+1:0;r>=need?finish(700):q()}q()}
function pattern(){let r=0,need=clamp(4+Math.floor(tier()/2),4,8);$('desc').textContent='Solve '+need+' number patterns.';function q(){let start=1+Math.floor(Math.random()*8),step=1+Math.floor(Math.random()*(5+tier())),a=[start,start+step,start+2*step,start+3*step],ans=start+4*step,opts=[ans,ans+step,ans-step].sort(()=>Math.random()-.5);$('stage').innerHTML='<h2>'+a.join(', ')+', ?</h2>';opts.forEach(x=>$('stage').append(btn(x,()=>{r=x===ans?r+1:0;r>=need?finish():q()})))}q()}
function targetChase(){let hits=0,need=clamp(14+tier()*2,14,32),limit=clamp(16000-tier()*400,8000,16000),start=Date.now();$('desc').textContent='Catch '+need+' targets in '+(limit/1000).toFixed(1)+' seconds.';function q(){if(Date.now()-start>limit){hits=0;start=Date.now()}$('stage').innerHTML='';let b=btn('💥',()=>{hits++;hits>=need?finish(750):q()});b.style.cssText='position:relative;margin-left:'+Math.floor(Math.random()*70)+'%;margin-top:'+Math.floor(Math.random()*180)+'px';$('stage').append(b)}q()}
function trueFalse(){let n=0,need=clamp(6+tier(),6,12);$('desc').textContent='Get '+need+' facts right.';const qs=[['A week has 7 days',1],['10 × 10 is 100',1],['A triangle has 4 sides',0],['February normally has 28 days',1],['5 + 8 is 14',0],['A dozen is 12',1],['1000 metres is 1 km',1],['9 × 6 is 56',0],['A square has 4 equal sides',1],['60 seconds is one minute',1]];function q(){let x=qs[Math.floor(Math.random()*qs.length)];$('stage').innerHTML='<h2>'+x[0]+'</h2>';$('stage').append(btn('True',()=>hit(1)),btn('False',()=>hit(0)));function hit(v){n=v===x[1]?n+1:Math.max(0,n-1);n>=need?finish():q()}}q()}
function cardHunt(){let r=0,need=clamp(4+Math.floor(tier()/2),4,8),cards=clamp(5+Math.floor(tier()/2),5,10),peek=clamp(1100-tier()*45,500,1100);$('desc').textContent='Watch the ❤️ then find it. Win '+need+' rounds.';function q(){let win=Math.floor(Math.random()*cards);$('stage').innerHTML='';for(let i=0;i<cards;i++)$('stage').append(btn(i===win?'❤️':'🖤',()=>{}));setTimeout(()=>{$('stage').innerHTML='';for(let i=0;i<cards;i++)$('stage').append(btn('🂠',()=>{if(i===win){r++;r>=need?finish():q()}else{r=0;q()}}))},peek)}q()}
function fastMath(){let n=0,need=clamp(8+tier(),8,16),limit=clamp(28000-tier()*500,15000,28000),start=Date.now();$('desc').textContent='Get '+need+' sums right in '+(limit/1000).toFixed(0)+' seconds.';function q(){if(Date.now()-start>limit){n=0;start=Date.now()}let max=15+tier()*3,a=1+Math.floor(Math.random()*max),b=1+Math.floor(Math.random()*max),ans=a+b;$('stage').innerHTML='<h2>'+a+' + '+b+'</h2>';[ans,ans+1,ans-1].sort(()=>Math.random()-.5).forEach(x=>$('stage').append(btn(x,()=>{n=x===ans?n+1:Math.max(0,n-1);n>=need?finish(800):q()})))}q()}
function jackpot(){let rounds=0,need=clamp(2+Math.floor(tier()/2),2,6),range=clamp(5+Math.floor(tier()/2),5,10);$('desc').textContent='Jackpot: find '+need+' hidden numbers.';function q(){let target=1+Math.floor(Math.random()*range);$('stage').innerHTML='<h3>Pick the hidden number from 1–'+range+'</h3>';for(let i=1;i<=range;i++)$('stage').append(btn(i,()=>{if(i===target){rounds++;rounds>=need?finish(1000):q()}else{rounds=Math.max(0,rounds-1);q()}}))}q()}
function load(){$('reward').hidden=true;$('stage').hidden=false;hud();let fs=[memory,tapRush,odd,hilo,reaction,doors,maths,sequence,emojiHunt,treasure,scramble,stopClock,numberMemory,quickChoice,pattern,targetChase,trueFalse,cardHunt,fastMath,jackpot];fs[(level-1)%fs.length]()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=9').then(r=>r.update());hud();load();